<?php

namespace App\Tests\Front\Roles\RolePurchaser;

use App\Entity\Category;
use App\Entity\Client;
use App\Entity\Product;
use App\Tests\Front\BaseTest;
use Symfony\Component\HttpFoundation\Response;

class ProductManagementTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testListProducts(): void
    {
        $client = $this->login(parent::LOGIN_PURCHASER);

        $crawler = $client->request('GET', $this->generatePath('front_list', ['entity'=> 'product']));

        $count = $crawler->filter('.product-tr')->count();
        $total = $crawler->filter('.table')->first()->attr('data-total');

        self::assertEquals(10, $count);
        self::assertEquals(11, $total);
    }

    public function testCreateProduct(): void
    {
        $client = $this->login(parent::LOGIN_PURCHASER);

        $crawler = $client->request('GET', $this->generatePath('front_create', ['entity'=> 'product']));

        $category = $this->getRepository(Category::class)->findOneBy([
            'name' => 'Category 1',
            'company' => $this->getCompany('The Company')
        ]);

        $product = [
            'name' => 'Test Product',
            'tax' => Product::IVA_8,
            'price' => '20.00',
            'category' => $category,
            'minStock' => 1,
            'maxStock' => 100,
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);
        $form['product[tax]']->setValue($product['tax']);
        $form['product[price]']->setValue($product['price']);
        $form['product[category]']->setValue($product['category']->getId());
        $form['product[minStock]']->setValue($product['minStock']);
        $form['product[maxStock]']->setValue($product['maxStock']);

        $client->submit($form);

        $successLabel = $client->getCrawler()->filter('.alert-success')->first();

        self::assertEquals(
            'Se ha creado el producto Test Product correctamente.',
            trim($successLabel->html())
        );

        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'Test Product']);

        self::assertNotNull($product);
    }

    public function testProductEdited(): void
    {
        $client = $this->login(parent::LOGIN_PURCHASER);

        /** @var Product $categoryToEdit */
        $productToEdit = $this->getRepository(Product::class)->findOneBy([
            'name' => 'Product 1',
            'company' => $this->getCompany('Another company')
        ]);

        $crawler = $client->request(
            'GET',
            $this->generatePath('front_edit', ['entity'=>'product','id'=>$productToEdit->getId()])
        );

        $product = [
            'name' => 'Test Product',
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);

        $client->submit($form);

        $successLabel = $client->getCrawler()->filter('.alert-success')->first();

        self::assertEquals(
            'Se ha editado el producto Test Product correctamente.',
            trim($successLabel->html())
        );
    }

    public function testProductRemove():void
    {
        $client = $this->login(parent::LOGIN_PURCHASER);

        /** @var Client $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'Test Product']);
        $url = $this->generatePath('front_delete', ['entity'=>'product','id'=>$product->getId()]);
        $client->request('GET',$url);

        self::assertResponseStatusCodeSame(Response::HTTP_FORBIDDEN);
    }
}
