<?php


namespace App\Tests\Functional\Product;

use App\Entity\Category;
use App\Entity\Company;
use App\Entity\Product;
use App\Tests\Functional\BaseTest;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;

class ManagementTest extends BaseTest
{
    protected $token;

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->token = $this->getToken();
    }


    public function testReadAllProducts(): void
    {
        $response = static::createClient()->request('GET', parent::API . 'products', [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token']
            ]
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(11, $response['hydra:totalItems']);
    }

    public function testReadARandomProduct(): void
    {
        $products = static::$container->get('doctrine')->getRepository(Product::class)->findAll();

        /** @var Product $randomProduct */
        $randomProduct = $products[array_rand($products)];

        $response = static::createClient()->request('GET', parent::API . 'products/' . $randomProduct->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token']
            ]
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(
            $randomProduct->getName(),
            $response['name'],
            'The expected name was ' . $response['name'] . ' but ' . $randomProduct->getName() . ' has found'
        );
    }

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testAddAnProduct()
    {
        $category = static::$container->get('doctrine')
            ->getRepository(Category::class)
            ->findOneBy(['name' => 'The Category']);

        /** @var Company $company */
        $company = static::$container->get('doctrine')
            ->getRepository(Company::class)
            ->findOneBy([
                'name' => 'The Company'
            ]);

        $product = [
            'name' => 'test',
            'description' => 'test',
            'user' => parent::API . 'users/' . $this->getUser()->getId(),
            'company' => parent::API . 'companies/' . $company->getId(),
            'category' => parent::API . 'categories/' . $category->getId(),
        ];

        $response = static::createClient()->request('POST', parent::API . 'products', [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
                'Content-Type' => 'application/json'
            ],
            'body' => json_encode($product)
        ]);
        $this->assertResponseIsSuccessfulAndInJson();
        $response = json_decode($response->getContent(), true);

        $this->assertEquals(
            $product['name'],
            $response['name'],
            'The expected name was ' . $response['name'] . ' but ' . $response['name'] . ' has found'
        );
    }

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testEditARandomProduct(): void
    {
        $products = static::$container->get('doctrine')->getRepository(Product::class)->findAll();

        /** @var Product $randomProduct */
        $randomProduct = $products[array_rand($products)];

        $response = static::createClient()->request('PUT', parent::API . 'products/' . $randomProduct->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
                'Content-Type' => 'application/json'
            ],
            'body' => json_encode(['name' => 'Fake Product'])
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(
            'Fake Product',
            $response['name'],
            'The expected name was ' . $response['name'] . ' but ' . $randomProduct->getName() . ' has found'
        );
    }

    public function testDeleteARandomProduct(): void
    {
        $products = static::$container->get('doctrine')->getRepository(Product::class)->findAll();

        /** @var Product $randomProduct */
        $randomProduct = $products[array_rand($products)];

        $response = static::createClient()->request('DELETE', parent::API . 'products/' . $randomProduct->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
            ]
        ]);

        $this->assertResponseStatusCodeSame(204, 'The response is not 204');
    }
}
