<?php

namespace App\Tests\Front\Roles\Admin;

use App\Entity\Category;
use App\Entity\Product;
use App\Tests\Front\BaseTest;
use Symfony\Component\HttpFoundation\Response;

class ProductManagementTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        passthru(sprintf('php bin/console h:f:l -n --env=test -q'));
    }

    public function testListProducts(): void
    {
        $client = $this->login(parent::LOGIN_ADMIN);

        $crawler = $client->request('GET', $this->generatePath('front_list', ['entity' => 'product']));

        $count = $crawler->filter('.product-tr')->count();
        $total = $crawler->filter('.table')->first()->attr('data-total');

        self::assertEquals(10, $count);
        self::assertEquals(10, $total);
    }

    public function testCreateProduct(): void
    {
        $client = $this->login(parent::LOGIN_ADMIN);

        $crawler = $client->request('GET', $this->generatePath('front_create', ['entity' => 'product']));

        $category = $this->getRepository(Category::class)->findOneBy([
            'name' => 'Category 1',
            'company' => $this->getCompany('Another Company'),
        ]);

        $product = [
            'name' => 'Test Product',
            'price' => '20.00',
            'category' => $category,
            'barcode' => random_int(10000,9999999),
            'location' => 'Location',
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);
        $form['product[price]']->setValue($product['price']);
        $form['product[barcode]']->setValue($product['barcode']);
        $form['product[location]']->setValue($product['location']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $successLabel = $client->getCrawler()->filter('.alert-success')->first();

        self::assertEquals(
            'Se ha creado el producto Test Product correctamente.',
            trim($successLabel->html())
        );

        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'Test Product']);

        self::assertNotNull($product);
    }

    public function testProductEdited(): void
    {
        $client = $this->login(parent::LOGIN_ADMIN);

        /** @var Product $categoryToEdit */
        $productToEdit = $this->getRepository(Product::class)->findOneBy([
            'name' => 'Product 1',
            'company' => $this->getCompany('Another Company'),
        ]);

        $crawler = $client->request(
            'GET',
            $this->generatePath('front_edit', ['entity' => 'product', 'id' => $productToEdit->getId()])
        );

        $product = [
            'name' => 'Test Product',
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);

        $client->submit($form);

        $successLabel = $client->getCrawler()->filter('.alert-success')->first();

        self::assertEquals(
            'Se ha editado el producto Test Product correctamente.',
            trim($successLabel->html())
        );
    }

    public function testProductRemoved(): void
    {
        $client = $this->login(parent::LOGIN_ADMIN);

        /** @var Product $categoryToEdit */
        $productToEdit = $this->getRepository(Product::class)->findOneBy([
            'name' => 'Product 1',
            'company' => $this->getCompany('Another Company'),
        ]);

        $client->request(
            'GET',
            $this->generatePath('front_list', ['entity' => 'product'])
        );
        $client->request(
            'GET',
            $this->generatePath('front_delete', ['entity' => 'product', 'id' => $productToEdit->getId()])
        );

        self::assertResponseStatusCodeSame(Response::HTTP_FORBIDDEN);
    }
}
