<?php

namespace App\Tests\Front\Management\Admin;

use App\Entity\Category;
use App\Entity\Company;
use App\Entity\Product;
use App\Entity\ProductProvider;
use App\Entity\Provider;
use App\Tests\Front\BaseTest;

class ProductProviderManagementTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testListProvidersOfProducts(): void
    {
        $client = $this->login(parent::LOGIN_ADMIN);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy([
            'name' => 'Product 1',
            'company' => $this->getRepository(Company::class)->findOneBy(['name' => 'Another Company'])
        ]);

        $crawler = $client->request('GET', $this->generatePath('front_edit', [
            'entity' => 'product',
            'id' => $product->getId()
        ]));

        $count = $crawler->filter('.product_provider-tr')->count();
        $total = $crawler->filter('.table')->first()->attr('data-total');

        self::assertEquals(1, $count);
        self::assertEquals(1, $total);
    }


    public function testAddProviderToProduct(): void
    {
        $client = $this->login(parent::LOGIN_ADMIN);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);

        $crawler = $client->request('GET', $this->generatePath('front_create', [
            'entity' => 'productProvider',
            'product' => $product->getId()
        ]));

        $data = [
            'price' => '20.00',
            'provider' => $this->getRepository(Provider::class)->findOneBy([
                'name' => 'Provider 9',
                'company' => $this->getRepository(Company::class)->findOneBy(['name' => 'Another Company'])
            ]),
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product_provider[price]']->setValue($data['price']);
        $form['product_provider[provider]']->setValue($data['provider']->getId());

        $client->submit($form);

        $successLabel = $client->getCrawler()->filter('.alert-success')->first();

        self::assertEquals(
            'Se ha añadido el precio al The Product correctamente.',
            trim($successLabel->html())
        );

        $productProvider = $this->getRepository(ProductProvider::class)->findOneBy([
            'product' => $product,
            'provider' => $data['provider']
        ]);

        self::assertInstanceOf(ProductProvider::class,$productProvider);
    }

    public function testProductEdited(): void
    {
        $client = $this->login(parent::LOGIN_ADMIN);

        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'Another Product']);
        $provider = $this->getRepository(Provider::class)->findOneBy(['name' => 'Another Provider']);
        $company = $this->getRepository(Company::class)->findOneBy(['name' => 'Another Company']);

        /** @var ProductProvider $productProvider */
        $productProvider = $this->getRepository(ProductProvider::class)->findOneBy([
            'product' => $product,
            'provider' => $provider,
            'company' => $company
        ]);

        $crawler = $client->request(
            'GET',
            $this->generatePath('front_edit', ['entity' => 'productProvider', 'id' => $productProvider->getId()])
        );

        $product = [
            'price' => '10',
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product_provider[price]']->setValue($product['price']);

        $client->submit($form);

        $successLabel = $client->getCrawler()->filter('.alert-success')->first();

        self::assertEquals(
            'Se ha editado el precio al Another Product correctamente.',
            trim($successLabel->html())
        );
    }

}
