<?php

namespace App\Tests\Front\Roles\RoleSeller;

use App\Entity\Category;
use App\Entity\Company;
use App\Entity\Product;
use App\Entity\ProductProvider;
use App\Entity\Provider;
use App\Tests\Front\BaseTest;
use Symfony\Component\HttpFoundation\Response;

class ProductProviderManagementTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testListProvidersOfProducts(): void
    {
        $client = $this->login(parent::LOGIN_SELLER);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);

        $crawler = $client->request('GET', $this->generatePath('front_edit', [
            'entity' => 'product',
            'id' => $product->getId()
        ]));

        $count = $crawler->filter('.product_provider-tr')->count();
        $total = $crawler->filter('.table')->first()->attr('data-total');

        self::assertEquals(1, $count);
        self::assertEquals(1, $total);
    }


    public function testAddProviderToProduct(): void
    {
        $client = $this->login(parent::LOGIN_SELLER);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);

        $client->request('GET', $this->generatePath('front_create', [
            'entity' => 'productProvider',
            'product' => $product->getId()
        ]));

        $response = $client->getResponse();

        self::assertEquals(Response::HTTP_FORBIDDEN, $response->getStatusCode());
    }

    public function testProductEdited(): void
    {
        $client = $this->login(parent::LOGIN_SELLER);

        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);
        $provider = $this->getRepository(Provider::class)->findOneBy(['name' => 'The Provider']);

        /** @var ProductProvider $productProvider */
        $productProvider = $this->getRepository(ProductProvider::class)->findOneBy([
            'product' => $product,
            'provider' => $provider
        ]);

        $client->request(
            'GET',
            $this->generatePath('front_edit', ['entity' => 'productProvider', 'id' => $productProvider->getId()])
        );

        $response = $client->getResponse();

        self::assertEquals(Response::HTTP_FORBIDDEN, $response->getStatusCode());
    }

}
