<?php

namespace App\Tests\Front\Roles\RoleSeller;

use App\Tests\Front\BaseTest;
use Symfony\Component\HttpFoundation\Response;

class PurchaseManagementTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        passthru(sprintf('php bin/console h:f:l -n --env=test -q'));
    }

    public function testListPurchases(): void
    {
        $client = $this->login(parent::LOGIN_SELLER);

        $client->request(
            'GET',
            $this->generatePath('front_list', ['entity' => 'purchase', 'sort' => 'reference'])
        );

        $response = $client->getResponse();

        self::assertEquals(Response::HTTP_FORBIDDEN, $response->getStatusCode());
    }

    public function testCreatePurchase(): void
    {
        $client = $this->login(parent::LOGIN_SELLER);

        $client->request('GET', $this->generatePath('front_create', ['entity' => 'purchase']));

        $response = $client->getResponse();

        self::assertEquals(Response::HTTP_FORBIDDEN, $response->getStatusCode());
    }

    public function testRemovePurchase(): void
    {
        $client = $this->login(parent::LOGIN_SELLER);
        $purchase = $this->createPurchase('carlos.sgude@gmail.com', 'The Provider', 'test');

        $url = $this->generatePath('front_delete', ['entity' => 'purchase', 'id' => $purchase->getId()]);
        $client->request('POST', $url);

        self::assertResponseStatusCodeSame(Response::HTTP_FORBIDDEN);
    }
}
