<?php

namespace App\Tests\Front\Roles\RoleGod;

use App\Entity\Provider;
use App\Entity\Purchase;
use App\Tests\Front\BaseTest;

class PurchaseManagementTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        passthru(sprintf('php bin/console h:f:l -n --env=test -q'));
    }

    public function testListPurchases(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        $crawler = $client->request(
            'GET',
            $this->generatePath('front_list', ['entity'=>'purchase','sort'=>'reference'])
        );

        $count = $crawler->filter('.purchase-tr')->count();
        $total = $crawler->filter('.table')->first()->attr('data-total');

        self::assertEquals(4, $count);
        self::assertEquals(4, $total);
    }

    public function testCreatePurchase(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        $crawler = $client->request('GET', $this->generatePath('front_create', ['entity'=>'purchase']));

        $purchase = [
            'reference' => 'Test',
            'provider' => $this->getRepository(Provider::class)->findOneBy(['name' => 'The Provider']),
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['purchase[reference]']->setValue($purchase['reference']);
        $form['purchase[provider]']->setValue($purchase['provider']->getId());

        $client->submit($form);

        $successLabel = $client->getCrawler()->filter('.alert-success')->first();

        self::assertEquals(
            'Se ha creado una nueva compra con la referencia Test.',
            trim($successLabel->html())
        );

        $provider = $this->getRepository(Purchase::class)->findOneBy(['reference' => 'Test']);

        self::assertNotNull($provider);
    }

    public function testRemovePurchase(): void
    {
        $client = $this->login(parent::LOGIN_GOD);
        $this->createPurchase('carlos.sgude@gmail.com', 'The Provider', 'test');
        $crawler = $client->request(
            'GET',
            $this->generatePath('front_list', ['entity'=>'purchase','sort'=>'reference'])
        );

        $count = $crawler->filter('.purchase-tr')->count();
        $total = $crawler->filter('.table')->first()->attr('data-total');

        self::assertEquals(5, $count);
        self::assertEquals(5, $total);

        $delete = $crawler->filter('.delete');
        $client->request('POST', $delete->first()->attr('data-href'));
        $crawler = $client->request(
            'GET',
            $this->generatePath('front_list', ['entity'=>'purchase','sort'=>'reference'])
        );

        $count = $crawler->filter('.purchase-tr')->count();
        $total = $crawler->filter('.table')->first()->attr('data-total');

        self::assertEquals(4, $count);
        self::assertEquals(4, $total);
    }
}
