<?php


namespace App\Tests\Functional\User;

use App\Entity\User;
use App\Tests\Functional\BaseTest;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;

/**
 * Class ManagementTest
 * @package App\Tests\Functional\User
 */
class ManagementTest extends BaseTest
{
    /**
     * @var array
     */
    protected $token;

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->token = $this->getToken();
    }


    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testReadAllUsers(): void
    {
        $response = static::createClient()->request('GET', parent::API . 'users', [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token']
            ]
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(11, $response['hydra:totalItems']);
    }

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testReadARandomUser(): void
    {
        $users = static::$container->get('doctrine')->getRepository(User::class)->findAll();

        /** @var User $randomUser */
        $randomUser = $users[array_rand($users)];

        $response = static::createClient()->request('GET', parent::API . 'users/' . $randomUser->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token']
            ]
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(
            $randomUser->getEmail(),
            $response['email'],
            'The expected email was ' . $response['email'] . ' but ' . $randomUser->getEmail() . ' has found'
        );
    }

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testAddAnUser(): void
    {
        $user = [
            'email' => 'test@email.com',
            'name' => 'test',
            'password' => 'test',
            'company' => parent::API . 'companies/' . $this->getCompany()->getId()
        ];

        $response = static::createClient()->request('POST', parent::API . 'users', [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
                'Content-Type' => 'application/json'
            ],
            'body' => json_encode($user)
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(
            $user['email'],
            $response['email'],
            'The expected email was ' . $response['email'] . ' but ' . $user['email'] . ' has found'
        );
    }

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testEditARandomUser(): void
    {
        $users = static::$container->get('doctrine')->getRepository(User::class)->findAll();

        /** @var User $randomUser */
        $randomUser = $users[array_rand($users)];

        $response = static::createClient()->request('PUT', parent::API . 'users/' . $randomUser->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
                'Content-Type' => 'application/json'
            ],
            'body' => json_encode(['name' => 'Fake User'])
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(
            'Fake User',
            $response['name'],
            'The expected email was ' . $response['email'] . ' but ' . $randomUser->getEmail() . ' has found'
        );
    }

    /**
     * @throws TransportExceptionInterface
     */
    public function testDeleteARandomUser(): void
    {
        $user = static::$container->get('doctrine')->getRepository(User::class)->findOneBy([
            'email' => 'another_user@fakemail.com'
        ]);

        static::createClient()->request('DELETE', parent::API . 'users/' . $user->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
            ]
        ]);

        self::assertResponseStatusCodeSame(204, 'The response is not 204');
    }
}
