<?php


namespace App\Tests\Functional\Company;

use App\Entity\Company;
use App\Tests\Functional\BaseTest;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;

class ManagementTest extends BaseTest
{
    protected $token;

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->token = $this->getToken();
    }


    public function testReadAllCompanies(): void
    {
        $response = static::createClient()->request('GET', parent::API . 'companies', [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token']
            ]
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(11, $response['hydra:totalItems']);
    }

    public function testReadARandomCompany(): void
    {
        $companies = static::$container->get('doctrine')->getRepository(Company::class)->findAll();

        /** @var Company $randomCompany */
        $randomCompany = $companies[array_rand($companies)];

        $response = static::createClient()->request('GET', parent::API . 'companies/' . $randomCompany->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token']
            ]
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(
            $randomCompany->getName(),
            $response['name'],
            'The expected name was ' . $response['name'] . ' but ' . $randomCompany->getName() . ' has found'
        );
    }

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testAddAnCompany()
    {
        $company = ['name' => 'test', 'description' => 'test', 'user' => parent::API . 'users/' . $this->getUser()->getId()];

        $response = static::createClient()->request('POST', parent::API . 'companies', [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
                'Content-Type' => 'application/json'
            ],
            'body' => json_encode($company)
        ]);
        $this->assertResponseIsSuccessfulAndInJson();
        $response = json_decode($response->getContent(), true);

        $this->assertEquals(
            $company['name'],
            $response['name'],
            'The expected name was ' . $response['name'] . ' but ' . $response['name'] . ' has found'
        );
    }

    /**
     * @throws ClientExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testEditARandomCompany(): void
    {
        $companies = static::$container->get('doctrine')->getRepository(Company::class)->findAll();

        /** @var Company $randomCompany */
        $randomCompany = $companies[array_rand($companies)];

        $response = static::createClient()->request('PUT', parent::API . 'companies/' . $randomCompany->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
                'Content-Type' => 'application/json'
            ],
            'body' => json_encode(['name' => 'Fake Company'])
        ]);

        $response = json_decode($response->getContent(), true);

        $this->assertResponseIsSuccessfulAndInJson();
        $this->assertEquals(
            'Fake Company',
            $response['name'],
            'The expected name was ' . $response['name'] . ' but ' . $randomCompany->getName() . ' has found'
        );
    }

    public function testDeleteARandomCompany(): void
    {
        $companies = static::$container->get('doctrine')->getRepository(Company::class)->findAll();

        /** @var Company $randomCompany */
        $randomCompany = $companies[array_rand($companies)];

        $response = static::createClient()->request('DELETE', parent::API . 'companies/' . $randomCompany->getId(), [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->token['token'],
            ]
        ]);

        $this->assertResponseStatusCodeSame(204, 'The response is not 204');
    }
}
