<?php

namespace App\Tests\Front\Validation;

use App\Entity\Category;
use App\Tests\Front\BaseTest;
use Symfony\Component\DomCrawler\Form;

class ProductValidationTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        passthru(sprintf('php bin/console h:f:l -n --env=test -q'));
    }

    public function testNameRequired(): void
    {
        $client = $this->login(['email' => 'carlos.sgude@gmail.com', 'password' => 'pasalacabra']);

        $crawler = $client->request('GET', '/create/product');

        $product = [
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
            'price' => 100,
            'tax' => Category::IVA_8,
            'minStock' => 1,
            'maxStock' => 100,
        ];

        /** @var Form $form */
        $form = $crawler->selectButton('Guardar')->form();

        $form['product[price]']->setValue($product['price']);
        $form['product[tax]']->setValue($product['tax']);
        $form['product[minStock]']->setValue($product['minStock']);
        $form['product[maxStock]']->setValue($product['maxStock']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor no debería estar vacío.', $errorSpan->html());
    }

    public function testPriceIsRequired(): void
    {
        $client = $this->login(['email' => 'carlos.sgude@gmail.com', 'password' => 'pasalacabra']);

        $crawler = $client->request('GET', '/create/product');

        $product = [
            'name' => 'Product Name',
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
            'tax' => Category::IVA_8,
            'minStock' => 1,
            'maxStock' => 100,
        ];

        /** @var Form $form */
        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);
        $form['product[tax]']->setValue($product['tax']);
        $form['product[minStock]']->setValue($product['minStock']);
        $form['product[maxStock]']->setValue($product['maxStock']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor que 0.', $errorSpan->html());
    }

    public function testMinStockGreaterThanOne(): void
    {
        $client = $this->login(['email' => 'carlos.sgude@gmail.com', 'password' => 'pasalacabra']);

        $crawler = $client->request('GET', '/create/product');

        $product = [
            'name' => 'The Name',
            'tax' => Category::IVA_8,
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
            'maxStock' => 1,
            'minStock' => '-1',
            'price' => 20,
        ];

        /** @var Form $form */
        $form = $crawler->selectButton('Guardar')->form();

        $form['product[price]']->setValue($product['price']);
        $form['product[name]']->setValue($product['name']);
        $form['product[tax]']->setValue($product['tax']);
        $form['product[maxStock]']->setValue($product['maxStock']);
        $form['product[minStock]']->setValue($product['minStock']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor o igual que 0.', $errorSpan->html());
    }

    public function testMaxStockGreaterThanOne(): void
    {
        $client = $this->login(['email' => 'carlos.sgude@gmail.com', 'password' => 'pasalacabra']);

        $crawler = $client->request('GET', '/create/product');

        $product = [
            'name' => 'The Name',
            'tax' => Category::IVA_8,
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
            'maxStock' => '-1',
            'minStock' => 1,
            'price' => 20,
        ];

        /** @var Form $form */
        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);
        $form['product[price]']->setValue($product['price']);
        $form['product[tax]']->setValue($product['tax']);
        $form['product[maxStock]']->setValue($product['maxStock']);
        $form['product[minStock]']->setValue($product['minStock']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor o igual que 1.', $errorSpan->html());
    }

    public function testMaxStockLowerThanMinStockRequired(): void
    {
        $client = $this->login(['email' => 'carlos.sgude@gmail.com', 'password' => 'pasalacabra']);

        $crawler = $client->request('GET', '/create/product');

        $product = [
            'name' => 'The Name',
            'tax' => Category::IVA_8,
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
            'maxStock' => 1,
            'minStock' => 100,
            'price' => 20,
        ];

        /** @var Form $form */
        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);
        $form['product[price]']->setValue($product['price']);
        $form['product[tax]']->setValue($product['tax']);
        $form['product[maxStock]']->setValue($product['maxStock']);
        $form['product[minStock]']->setValue($product['minStock']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor o igual que 100.', $errorSpan->html());
    }
}
