<?php

namespace App\Tests\Front\Validation;

use App\Entity\Category;
use App\Entity\MediaObject;
use App\Entity\Product;
use App\Tests\Front\BaseTest;

class ProductValidationTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        passthru(sprintf('php bin/console h:f:l -n --env=test -q'));
    }

    public function testNameRequired(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        $crawler = $client->request('GET', $this->generatePath('front_create', ['entity' => 'product']));
        $product = [
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
            'price' => 100,
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[price]']->setValue($product['price']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor no debería estar vacío.', $errorSpan->html());
    }

    public function testPriceIsRequired(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        $crawler = $client->request('GET', $this->generatePath('front_create', ['entity' => 'product']));

        $product = [
            'name' => 'Product Name',
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor que 0.', $errorSpan->html());
    }

    public function testMinStockGreaterThanOne(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);
        $url =$this->generatePath('front_edit', ['entity' => 'product','id' => $product->getId()]);
        $crawler = $client->request('GET', $url);

        $product = ['minStock' => '-1','maxStock'=> 100];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[maxStock]']->setValue($product['maxStock']);
        $form['product[minStock]']->setValue($product['minStock']);

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor o igual que 0.', $errorSpan->html());
    }

    public function testMaxStockGreaterThanOne(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);
        $url =$this->generatePath('front_edit', ['entity' => 'product','id' => $product->getId()]);
        $crawler = $client->request('GET', $url);

        $product = ['maxStock' => '-1',];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[maxStock]']->setValue($product['maxStock']);

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor o igual que 10.', $errorSpan->html());
    }

    public function testMaxStockLowerThanMinStockRequired(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);
        $url =$this->generatePath('front_edit', ['entity' => 'product','id' => $product->getId()]);
        $crawler = $client->request('GET', $url);

        $product = [
            'maxStock' => 1,
            'minStock' => 100,
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[maxStock]']->setValue($product['maxStock']);
        $form['product[minStock]']->setValue($product['minStock']);

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser mayor o igual que 100.', $errorSpan->html());
    }

    public function testCreateProductWithPrincipalImage(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        $crawler = $client->request('GET', $this->generatePath('front_create', ['entity' => 'product']));

        $product = [
            'name' => 'Test Product',
            'price' => '20.00',
            'category' => $this->getRepository(Category::class)->findOneBy(['name' => 'The Category']),
            'image' => $this->getFile('document.pdf','document.pdf')
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product[name]']->setValue($product['name']);
        $form['product[image]']->setValue($product['image']);
        $form['product[price]']->setValue($product['price']);
        $form['product[category]']->setValue($product['category']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals(0,$crawler->filter('img#avatar')->count());
        self::assertEquals('El archivo no es una imagen válida.', $errorSpan->html());
    }
}
