<?php

namespace App\Tests\Front\Validation;

use App\Entity\Category;
use App\Entity\Company;
use App\Entity\Product;
use App\Entity\ProductProvider;
use App\Entity\Provider;
use App\Tests\Front\BaseTest;

class ProductProviderValidationTest extends BaseTest
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        passthru(sprintf('php bin/console h:f:l -n --env=test -q'));
    }

    public function testPriceIsRequired(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);

        $crawler = $client->request('GET', $this->generatePath('front_create', [
            'entity' => 'productProvider',
            'product' => $product->getId()
        ]));

        $data = [
            'provider' => $this->getRepository(Provider::class)->findOneBy([
                'name' => 'Provider 9',
                'company' => $this->getRepository(Company::class)->findOneBy(['name' => 'The Company'])
            ]),
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product_provider[provider]']->setValue($data['provider']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor no debería estar vacío.', $errorSpan->html());
    }

    public function testProviderIsRequired(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);

        $crawler = $client->request('GET', $this->generatePath('front_create', [
            'entity' => 'productProvider',
            'product' => $product->getId()
        ]));

        $data = [
            'price' => 20
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product_provider[price]']->setValue($data['price']);

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor no debería estar vacío.', $errorSpan->html());
    }

    public function testPriceMustBeLowerThanOfProduct(): void
    {
        $client = $this->login(parent::LOGIN_GOD);

        /** @var Product $product */
        $product = $this->getRepository(Product::class)->findOneBy(['name' => 'The Product']);

        $crawler = $client->request('GET', $this->generatePath('front_create', [
            'entity' => 'productProvider',
            'product' => $product->getId()
        ]));

        $data = [
            'price' => 99999999,
            'provider' => $this->getRepository(Provider::class)->findOneBy([
                'name' => 'Provider 9',
                'company' => $this->getRepository(Company::class)->findOneBy(['name' => 'The Company'])
            ]),
        ];

        $form = $crawler->selectButton('Guardar')->form();

        $form['product_provider[price]']->setValue($data['price']);
        $form['product_provider[provider]']->setValue($data['provider']->getId());

        $client->submit($form);

        $errorSpan = $client->getCrawler()->filter('.form-error-message')->first();

        self::assertEquals('Este valor debería ser menor o igual que 100.', $errorSpan->html());
    }
}
