<?php

namespace App\Security;

abstract class AbstractUserRoles
{
    public const ROLE_GOD = 'ROLE_GOD';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    public const ROLE_DELETE_CATEGORY = 'ROLE_DELETE_CATEGORY';
    public const ROLE_READ_CATEGORY = 'ROLE_READ_CATEGORY';
    public const ROLE_CREATE_CATEGORY = 'ROLE_CREATE_CATEGORY';
    public const ROLE_UPDATE_CATEGORY = 'ROLE_UPDATE_CATEGORY';

    public const ROLE_DELETE_CLIENT = 'ROLE_DELETE_CLIENT';
    public const ROLE_READ_CLIENT = 'ROLE_READ_CLIENT';
    public const ROLE_CREATE_CLIENT = 'ROLE_CREATE_CLIENT';
    public const ROLE_UPDATE_CLIENT = 'ROLE_UPDATE_CLIENT';

    public const ROLE_DELETE_PRODUCT = 'ROLE_DELETE_PRODUCT';
    public const ROLE_READ_PRODUCT = 'ROLE_READ_PRODUCT';
    public const ROLE_CREATE_PRODUCT = 'ROLE_CREATE_PRODUCT';
    public const ROLE_UPDATE_PRODUCT = 'ROLE_UPDATE_PRODUCT';

    public const ROLE_DELETE_PROVIDER = 'ROLE_DELETE_PROVIDER';
    public const ROLE_READ_PROVIDER = 'ROLE_READ_PROVIDER';
    public const ROLE_CREATE_PROVIDER = 'ROLE_CREATE_PROVIDER';
    public const ROLE_UPDATE_PROVIDER = 'ROLE_UPDATE_PROVIDER';

    public const ROLE_DELETE_PURCHASE = 'ROLE_DELETE_PURCHASE';
    public const ROLE_READ_PURCHASE = 'ROLE_READ_PURCHASE';
    public const ROLE_CREATE_PURCHASE = 'ROLE_CREATE_PURCHASE';
    public const ROLE_UPDATE_PURCHASE = 'ROLE_UPDATE_PURCHASE';

    public const ROLE_DELETE_PURCHASE_LINE = 'ROLE_DELETE_PURCHASE_LINE';
    public const ROLE_READ_PURCHASE_LINE = 'ROLE_READ_PURCHASE_LINE';
    public const ROLE_CREATE_PURCHASE_LINE = 'ROLE_CREATE_PURCHASE_LINE';
    public const ROLE_UPDATE_PURCHASE_LINE = 'ROLE_UPDATE_PURCHASE_LINE';

    public const ROLE_DELETE_USER = 'ROLE_DELETE_USER';
    public const ROLE_READ_USER = 'ROLE_READ_USER';
    public const ROLE_CREATE_USER = 'ROLE_CREATE_USER';
    public const ROLE_UPDATE_USER = 'ROLE_UPDATE_USER';

    public const ROLE_DELETE_COMPANY = 'ROLE_DELETE_COMPANY';
    public const ROLE_READ_COMPANY = 'ROLE_READ_COMPANY';
    public const ROLE_CREATE_COMPANY = 'ROLE_CREATE_COMPANY';
    public const ROLE_UPDATE_COMPANY = 'ROLE_UPDATE_COMPANY';

    public const ROLE_DELETE_PRODUCT_PROVIDER = 'ROLE_DELETE_PRODUCT_PROVIDER';
    public const ROLE_READ_PRODUCT_PROVIDER = 'ROLE_READ_PRODUCT_PROVIDER';
    public const ROLE_CREATE_PRODUCT_PROVIDER = 'ROLE_CREATE_PRODUCT_PROVIDER';
    public const ROLE_UPDATE_PRODUCT_PROVIDER = 'ROLE_UPDATE_PRODUCT_PROVIDER';
}
